### ISSUE TITLE
Add a leave button

### ISSUE THREAD

**Issue by AliceKawanami** [theca11/whack-a-mole#1]
### What you request
I would like a way to leave the game and return to a previous screen? maybe by long pressing the score?

### Why you request it
It'd be a great quality of life improvement

**Comment by theca11** [comment]
This would be a nice QoL feature indeed. Unfortunately, right now it can't be implemented within the plugin due to Stream Deck limitations. I'll leave this issue open in case the SDK updates in the future and allows for this feature.

That said, you can edit the Whack-a-mole profile as much as you like - the game won't break if you add/remove/reorganize any of the keys. So while it's not the ideal solution, you can replace one of the mole tiles with a native Stream Deck navigation key such as `Switch Profile`.

**Comment by theca11** [comment]
Update v1.1.0 of the plugin now solves this issue. There's a new plugin action that you can use to go to the installed game profile. If you use this action to navigate there, then you can exit the game by holding the Start/Exit button, which will return you to the previous profile

Note that if you switch to the game profile by other means (e.g. using a native Switch Profile key or the software dropdown menu) exiting the game will not work due to current SDK limitations.
